// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package gen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Request) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type Response struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ArrayRequest struct {
	ListRequest          int64    `protobuf:"varint,1,opt,name=listRequest,proto3" json:"listRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayRequest) Reset()         { *m = ArrayRequest{} }
func (m *ArrayRequest) String() string { return proto.CompactTextString(m) }
func (*ArrayRequest) ProtoMessage()    {}
func (*ArrayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ArrayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayRequest.Unmarshal(m, b)
}
func (m *ArrayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayRequest.Marshal(b, m, deterministic)
}
func (m *ArrayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayRequest.Merge(m, src)
}
func (m *ArrayRequest) XXX_Size() int {
	return xxx_messageInfo_ArrayRequest.Size(m)
}
func (m *ArrayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayRequest proto.InternalMessageInfo

func (m *ArrayRequest) GetListRequest() int64 {
	if m != nil {
		return m.ListRequest
	}
	return 0
}

type ArrayResponse struct {
	ListResponse         []int64  `protobuf:"varint,1,rep,packed,name=listResponse,proto3" json:"listResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayResponse) Reset()         { *m = ArrayResponse{} }
func (m *ArrayResponse) String() string { return proto.CompactTextString(m) }
func (*ArrayResponse) ProtoMessage()    {}
func (*ArrayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ArrayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayResponse.Unmarshal(m, b)
}
func (m *ArrayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayResponse.Marshal(b, m, deterministic)
}
func (m *ArrayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayResponse.Merge(m, src)
}
func (m *ArrayResponse) XXX_Size() int {
	return xxx_messageInfo_ArrayResponse.Size(m)
}
func (m *ArrayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayResponse proto.InternalMessageInfo

func (m *ArrayResponse) GetListResponse() []int64 {
	if m != nil {
		return m.ListResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*ArrayRequest)(nil), "proto.ArrayRequest")
	proto.RegisterType((*ArrayResponse)(nil), "proto.ArrayResponse")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x89, 0xa1, 0xbb, 0xcb, 0xb3, 0xab, 0x10, 0x45, 0x4a, 0x4f, 0x25, 0xa0, 0x14, 0x84,
	0x2a, 0xed, 0xd1, 0x53, 0xbd, 0x7b, 0x89, 0x37, 0x6f, 0xad, 0x79, 0x48, 0x21, 0xb4, 0x35, 0x49,
	0x85, 0xfe, 0x10, 0xff, 0xaf, 0xd8, 0x3c, 0xa5, 0x3d, 0xed, 0x29, 0x7c, 0x33, 0xf3, 0x86, 0x0c,
	0x1c, 0x1d, 0xda, 0xaf, 0xee, 0x1d, 0x8b, 0xd1, 0x0e, 0x7e, 0x10, 0xd1, 0xf2, 0xc8, 0x5b, 0xd8,
	0x2b, 0xfc, 0x9c, 0xd0, 0x79, 0x11, 0x03, 0x6b, 0x12, 0x96, 0xb1, 0x9c, 0x2b, 0xd6, 0xfc, 0x52,
	0x9b, 0x9c, 0x05, 0x6a, 0xa5, 0x84, 0x83, 0x42, 0x37, 0x0e, 0xbd, 0x43, 0x71, 0x03, 0x3b, 0x8b,
	0x6e, 0x32, 0x9e, 0xc2, 0x44, 0xf2, 0x11, 0xe2, 0xda, 0xda, 0x66, 0xfe, 0xeb, 0xcb, 0xe0, 0xdc,
	0x74, 0xce, 0x13, 0x52, 0x78, 0x2d, 0xc9, 0x0a, 0x8e, 0x74, 0x41, 0xd5, 0x12, 0xe2, 0xe0, 0x07,
	0x4e, 0x58, 0xc6, 0x73, 0xae, 0x36, 0x5a, 0xf9, 0xcd, 0x00, 0x6a, 0xad, 0x5f, 0xc3, 0x1a, 0x71,
	0x07, 0xbc, 0xd6, 0x5a, 0x5c, 0x84, 0x59, 0x05, 0x55, 0xa7, 0x97, 0xff, 0x4c, 0xd5, 0xf7, 0x70,
	0x78, 0x99, 0x8c, 0xef, 0x46, 0x33, 0x9f, 0x0e, 0x97, 0x10, 0x2d, 0x1f, 0x13, 0x57, 0xe4, 0xac,
	0x87, 0xa5, 0xd7, 0x5b, 0x31, 0xdc, 0x3c, 0xef, 0xdf, 0xa2, 0x87, 0xa7, 0x0f, 0xec, 0xdb, 0xdd,
	0xe2, 0x56, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x7f, 0x3d, 0xd2, 0x71, 0x01, 0x00, 0x00,
}
